(function(){
const notified=new Set(JSON.parse(sessionStorage.getItem('teaching-notified')||'[]'));
const L=(zh,en)=>window.I18n?.pick?window.I18n.pick(zh,en):zh;
function b64(s){const p='='.repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function register(){if(!('serviceWorker'in navigator))return null;try{return await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e);return null}}
async function requestPermission(){if(!('Notification'in window))throw new Error(L('当前浏览器不支持系统通知。','This browser does not support system notifications.'));const p=await Notification.requestPermission();if(p!=='granted')throw new Error(L('通知权限未开启。','Notification permission was not granted.'));const r=await register();if(r)await r.showNotification('Teaching Tracker',{body:L('提醒已开启。','Reminders are enabled.'),icon:'./assets/icon-192.png',badge:'./assets/icon-192.png',tag:'permission-test'});return p}
async function enablePush(){const c=window.APP_CONFIG||{};if(!c.vapidPublicKey)throw new Error(L('请先在 js/config.js 填入 vapidPublicKey。','Add vapidPublicKey to js/config.js first.'));if(teachingDB.getMode()!=='cloud')throw new Error(L('后台 Push 需要先登入 Supabase。','Sign in to Supabase before enabling background Push.'));await requestPermission();const r=await navigator.serviceWorker.ready;let s=await r.pushManager.getSubscription();if(!s)s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(c.vapidPublicKey)});await teachingDB.savePushSubscription(s);return s}
async function checkDueTasks(){if(!('Notification'in window)||Notification.permission!=='granted'||!('serviceWorker'in navigator))return;const r=await navigator.serviceWorker.ready,s=teachingDB.getState();if(!s)return;const now=Date.now();for(const t of s.todos.filter(x=>!x.completed&&x.due_at&&x.reminder_minutes)){const when=new Date(t.due_at).getTime()-Number(t.reminder_minutes)*60000;if(now>=when&&now<new Date(t.due_at).getTime()+600000&&!notified.has(t.id)){const c=s.courses.find(x=>x.id===t.course_id);await r.showNotification(c?`${c.code} · ${L('任务提醒','Task Reminder')}`:L('任务提醒','Task Reminder'),{body:t.title,icon:'./assets/icon-192.png',badge:'./assets/icon-192.png',tag:`task-${t.id}`,data:{url:'./#tasks'}});notified.add(t.id)}}sessionStorage.setItem('teaching-notified',JSON.stringify([...notified]))}
register();setInterval(checkDueTasks,60000);setTimeout(checkDueTasks,2500);window.TeachingNotifications={register,requestPermission,enablePush,checkDueTasks};
})();
